# Generated by Django 3.2.6 on 2021-08-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('economy', models.BooleanField(default=False)),
                ('international', models.BooleanField(default=False)),
                ('technology', models.BooleanField(default=False)),
                ('sports', models.BooleanField(default=False)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
