# Generated by Django 3.2.6 on 2021-08-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xynonews', '0002_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='article',
            name='trend',
            field=models.BooleanField(default=False),
        ),
    ]
